### ISSUE TITLE
not working, more detailed tutorial?

### ISSUE THREAD

**Issue by zbb5049** [CraftTweaker/ZsLint#1]
I opened minecraft first with newest crafttweaker available on curseforge, typed /ct zslint on my client,  then opened the vs code, opened the script and save it. nothing shows up in my minecraft. 
I am not able to find any useful information to debug this. 
Could you please provide a more detailed tutorial?

**Comment by jaredlll08** [comment]
This project is no longer in use or supported, nor does it currently work.
